# Generated by Django 5.2 on 2025-05-09 13:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_podstrony', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(max_length=255)),
                ('tresc', models.TextField()),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('oferta_pozycja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='oferta_podstrony.oferta_pozycja')),
            ],
        ),
    ]
