# Generated by Django 5.2 on 2025-05-09 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_podstrony', '0002_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['kolejnosc']},
        ),
        migrations.RemoveField(
            model_name='oferta_pozycja',
            name='data',
        ),
        migrations.RemoveField(
            model_name='oferta_pozycja',
            name='kolejnosc',
        ),
        migrations.RemoveField(
            model_name='oferta_pozycja',
            name='link_przycisku',
        ),
        migrations.RemoveField(
            model_name='oferta_pozycja',
            name='plik',
        ),
        migrations.RemoveField(
            model_name='oferta_pozycja',
            name='styl',
        ),
        migrations.RemoveField(
            model_name='oferta_pozycja',
            name='tekst',
        ),
        migrations.RemoveField(
            model_name='oferta_pozycja',
            name='tekst_pliku',
        ),
        migrations.RemoveField(
            model_name='oferta_pozycja',
            name='tekst_przycisku',
        ),
        migrations.RemoveField(
            model_name='oferta_pozycja',
            name='zdjecie',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tresc',
        ),
        migrations.AddField(
            model_name='post',
            name='kolejnosc',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='link_przycisku',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='plik',
            field=models.FileField(blank=True, null=True, upload_to='pliki/'),
        ),
        migrations.AddField(
            model_name='post',
            name='styl',
            field=models.CharField(choices=[('default', 'Domyślny'), ('img-left', 'Obrazek po lewej'), ('img-right', 'Obrazek po prawej'), ('img-top', 'Obrazek na górze'), ('tiles', 'Kafelek')], default='default', max_length=90),
        ),
        migrations.AddField(
            model_name='post',
            name='tekst',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tekst_pliku',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='tekst_przycisku',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='zdjecie',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='aktualnosci/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tytul',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
