# Generated by Django 5.2 on 2025-05-09 15:48

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_podstrony', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oferta_pozycja',
            options={'verbose_name': 'Podstrona oferty', 'verbose_name_plural': 'Podstrony oferty'},
        ),
        migrations.AlterField(
            model_name='post',
            name='tekst',
            field=ckeditor.fields.RichTextField(blank=True, max_length=1000, null=True),
        ),
    ]
