# Generated by Django 5.2 on 2025-05-09 17:34

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_podstrony', '0005_alter_oferta_pozycja_options_alter_post_tekst'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='nazwa',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='tekst',
            field=ckeditor.fields.RichTextField(blank=True, max_length=60000, null=True),
        ),
    ]
