# Generated by Django 5.2 on 2025-05-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_podstrony', '0006_post_nazwa_alter_post_tekst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='nazwa',
        ),
    ]
