# Generated by Django 5.2 on 2025-05-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_podstrony', '0015_alter_post_styl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kolor',
            field=models.CharField(choices=[('kol-default', 'Biały'), ('kol-czarny', 'Czarny'), ('kol-niebieski', 'Niebiski'), ('kol-rozowy', 'Różowy')], default='default', max_length=90),
        ),
    ]
