# Generated by Django 5.2.1 on 2025-05-11 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_podstrony', '0022_alter_oferta_pozycja_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Zawartość podstrony', 'verbose_name_plural': 'Zawartość podstron'},
        ),
    ]
