# Generated by Django 5.2.1 on 2025-05-11 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_podstrony', '0023_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['kolejnosc'], 'verbose_name': 'Zawartość podstrony', 'verbose_name_plural': 'Zawartość podstron'},
        ),
    ]
