# Generated by Django 5.2.1 on 2025-05-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_podstrony', '0025_alter_oferta_pozycja_options_alter_post_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta_pozycja',
            name='kolejnosc',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
