# Generated by Django 5.2.1 on 2025-05-16 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_podstrony', '0027_alter_oferta_pozycja_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oferta_pozycja',
            options={'ordering': ['-kolejnosc'], 'verbose_name': 'Podstrona oferty', 'verbose_name_plural': 'Podstrony oferty'},
        ),
    ]
