# Generated by Django 5.2.1 on 2025-05-18 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_podstrony', '0029_alter_oferta_pozycja_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Oferta_pozycja',
            new_name='OfferItem',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='oferta_pozycja',
            new_name='OfferItem',
        ),
    ]
