# Generated by Django 5.2.1 on 2025-05-18 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_podstrony', '0030_rename_oferta_pozycja_offeritem_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='OfferItem',
            new_name='offer_item',
        ),
    ]
