# Generated by Django 5.2 on 2025-05-09 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oferta_pozycja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tytul', models.CharField(blank=True, max_length=1000, null=True)),
                ('tekst', models.TextField(blank=True, max_length=1000, null=True)),
                ('tekst_przycisku', models.CharField(blank=True, max_length=1000, null=True)),
                ('link_przycisku', models.CharField(blank=True, max_length=1000, null=True)),
                ('tekst_pliku', models.CharField(blank=True, max_length=1000, null=True)),
                ('plik', models.FileField(blank=True, null=True, upload_to='pliki/')),
                ('zdjecie', models.ImageField(blank=True, max_length=255, null=True, upload_to='aktualnosci/')),
                ('data', models.DateTimeField(default=django.utils.timezone.now)),
                ('styl', models.CharField(choices=[('default', 'Domyślny'), ('img-left', 'Obrazek po lewej'), ('img-right', 'Obrazek po prawej'), ('img-top', 'Obrazek na górze'), ('tiles', 'Kafelek')], default='default', max_length=90)),
                ('kolejnosc', models.PositiveIntegerField(default=0)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'oferta: pozycja',
                'verbose_name_plural': 'oferta: pozycje',
            },
        ),
    ]
