# Generated by Django 5.2 on 2025-05-09 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_podstrony', '0003_alter_post_options_remove_oferta_pozycja_data_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Zawartość podstrony', 'verbose_name_plural': 'Zawartość podstron'},
        ),
    ]
