# Generated by Django 5.2 on 2025-05-09 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_podstrony', '0007_remove_post_nazwa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oferta_pozycja',
            old_name='tytul',
            new_name='nazwa',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='tytul',
            new_name='nazwa',
        ),
    ]
