# Generated by Django 5.2 on 2025-05-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_podstrony', '0008_rename_tytul_oferta_pozycja_nazwa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tytul',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
