# Generated by Django 5.2 on 2025-05-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_podstrony', '0009_post_tytul'),
    ]

    operations = [
        migrations.AddField(
            model_name='oferta_pozycja',
            name='tytul',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
