# Generated by Django 5.2 on 2025-05-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_podstrony', '0013_post_kolor_alter_post_styl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='styl',
            field=models.CharField(choices=[('default', 'Tekst, zwykły'), ('default-j', 'Tekst, wyjustowany'), ('default-c', 'Tekst, wycentrowany'), ('default-k', 'Kursywa, wycentrowana'), ('wide-panel', 'Szeroki panel'), ('wide-tiles', 'Szeroki panel z kafelkami'), ('img-left-s', 'Obrazek z lewej, mały'), ('img-left-m', 'Obrazek z lewej, średni'), ('img-left-l', 'Obrazek z lewej, duży'), ('img-right-s', 'Obrazek z prawej, mały'), ('img-right-m', 'Obrazek z prawej, średni'), ('img-right-l', 'Obrazek z prawej, duży'), ('img-top-s', 'Obrazek na górze, mały'), ('img-top-l', 'Obrazek na górze, duży'), ('img-bot-m', 'Obrazek na dole, średni'), ('img-bot-xl', 'Obrazek na dole, XL')], default='default', max_length=90),
        ),
    ]
