# Generated by Django 5.2 on 2025-05-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_podstrony', '0017_alter_post_kolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kolor',
            field=models.CharField(choices=[('kol-bialy', 'Biały'), ('kol-czarny', 'Czarny'), ('kol-niebieski', 'Niebiski'), ('kol-rozowy', 'Różowy')], default='kol-bialy', max_length=90),
        ),
    ]
