# Generated by Django 5.2 on 2025-05-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_podstrony', '0018_alter_post_kolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='styl',
            field=models.CharField(choices=[('default', 'Tekst, zwykły'), ('default-j', 'Tekst, wyjustowany'), ('default-c', 'Tekst, wycentrowany'), ('wide-panel', 'Tekst, szeroki panel'), ('img-left-s', 'Obrazek z lewej, mały'), ('img-left-m', 'Obrazek z lewej, średni'), ('img-left-l', 'Obrazek z lewej, duży'), ('img-right-s', 'Obrazek z prawej, mały'), ('img-right-m', 'Obrazek z prawej, średni'), ('img-right-l', 'Obrazek z prawej, duży'), ('img-top', 'Obrazek na górze'), ('img-bot', 'Obrazek na dole')], default='default', max_length=90),
        ),
    ]
