# Generated by Django 5.2 on 2025-05-11 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_podstrony', '0021_alter_post_kolor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oferta_pozycja',
            options={'ordering': ['kolejnosc'], 'verbose_name': 'Podstrona oferty', 'verbose_name_plural': 'Podstrony oferty'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['kolejnosc'], 'verbose_name': 'Zawartość podstrony', 'verbose_name_plural': 'Zawartość podstron'},
        ),
        migrations.AddField(
            model_name='oferta_pozycja',
            name='kolejnosc',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
