# Generated by Django 5.2.1 on 2025-05-11 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_podstrony', '0024_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oferta_pozycja',
            options={'verbose_name': 'Podstrona oferty', 'verbose_name_plural': 'Podstrony oferty'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Zawartość podstrony', 'verbose_name_plural': 'Zawartość podstron'},
        ),
        migrations.RemoveField(
            model_name='oferta_pozycja',
            name='kolejnosc',
        ),
    ]
