# Generated by Django 5.2.1 on 2025-05-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oferta_podstrony', '0026_oferta_pozycja_kolejnosc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oferta_pozycja',
            options={'ordering': ['kolejnosc'], 'verbose_name': 'Podstrona oferty', 'verbose_name_plural': 'Podstrony oferty'},
        ),
        migrations.AlterField(
            model_name='oferta_pozycja',
            name='kolejnosc',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='post',
            name='kolor',
            field=models.CharField(choices=[('kol-bialy', 'Biały'), ('kol-szary', 'Szary'), ('kol-niebieski', 'Niebieski'), ('kol-zielony', 'Zielony'), ('kol-rozowy', 'Różowy')], default='kol-bialy', max_length=90),
        ),
    ]
