# Generated by Django 5.2.1 on 2025-05-18 16:25

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OfferItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Podstrona oferty',
                'verbose_name_plural': 'Podstrony oferty',
                'ordering': ['-order'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=1000, null=True)),
                ('title', models.CharField(blank=True, max_length=1000, null=True)),
                ('text', ckeditor.fields.RichTextField(blank=True, max_length=60000, null=True)),
                ('button_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('button_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('file_text', models.CharField(blank=True, max_length=1000, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='files/')),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='images/')),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('style', models.CharField(choices=[('default', 'Tekst, zwykły'), ('default-j', 'Tekst, wyjustowany'), ('default-c', 'Tekst, wycentrowany'), ('wide-panel', 'Tekst, szeroki panel'), ('img-left-s', 'Obrazek z lewej, mały'), ('img-left-m', 'Obrazek z lewej, średni'), ('img-left-l', 'Obrazek z lewej, duży'), ('img-right-s', 'Obrazek z prawej, mały'), ('img-right-m', 'Obrazek z prawej, średni'), ('img-right-l', 'Obrazek z prawej, duży'), ('img-top', 'Obrazek na górze'), ('img-bot', 'Obrazek na dole')], default='default', max_length=90)),
                ('color', models.CharField(choices=[('kol-bialy', 'Biały'), ('kol-szary', 'Szary'), ('kol-niebieski', 'Niebieski'), ('kol-zielony', 'Zielony'), ('kol-rozowy', 'Różowy')], default='kol-bialy', max_length=90)),
                ('order', models.PositiveIntegerField(default=0)),
                ('offer_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='offer_subpages.offeritem')),
            ],
            options={
                'verbose_name': 'Zawartość podstrony',
                'verbose_name_plural': 'Zawartość podstron',
            },
        ),
    ]
