# Generated by Django 5.2.1 on 2025-05-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer_subpages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='color',
            field=models.CharField(choices=[('color-white', 'Biały'), ('color-gray', 'Szary'), ('color-aqua', 'Błękitny'), ('color-blue', 'Niebieski'), ('color-green', 'Zielony'), ('color-pink', 'Różowy')], default='color-white', max_length=90),
        ),
    ]
